version: '3.8'

services:
  # sender
  sender:
    build: ./sender
    container_name: sender
    depends_on:
      - rabbit
    restart: on-failure
    networks:
      - sre-net
    ports:
      - "9090:9090"
  # receiver
  receiver:
    build: ./receiver
    container_name: receiver
    depends_on:
      - db
      - rabbit
    restart: on-failure

    networks:
      - db-net
      - sre-net

  # database
  db:
    image: postgres:15.3-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: receiver_user
      POSTGRES_PASSWORD: 2980
      POSTGRES_DB: tmp
    networks:
      - db-net
    volumes:
      - psql-vol:/var/lib/postgresql/data

  # nginx

  #rabbit
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rbt
    networks:
      - sre-net
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    ports:
      - "5672:5672"
      - "15672:15672"

# networks
networks:
  sre-net:
  db-net:

#volumes
volumes:
  psql-vol: