version: '3.8'

services:
  # sender
  sender:
    build: ./sender
    container_name: sender
    depends_on:
      - rabbit
    restart: on-failure
    networks:
      - sre-net
    ports:
      - "9090:9090"
  # receiver

  # database

  # nginx

  #rabbit
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rbt
    networks:
      - sre-net
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    ports:
      - "5672:5672"
      - "15672:15672"

# networks
networks:
  sre-net: