name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image

        run: make build  DOCKER_IMAGE_NAME="sender:latest" DOCKERFILE="./sender/Dockerfile"

      - name: push to docker
        run: docker build -t receiver:latest -f ./receiver/Dockerfile .


#  push:
#    runs-on: ubuntu-latest
#    needs: build
#

