name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t sender:latest -f ./sender/Dockerfile

      - name: push to docker
        run: docker build -t receiver:latest -f ./receiver/Dockerfile .


  push:
    runs-on: ubuntu-latest
    needs: build


