name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: make build ./sender/Dockerfile

      - name: push to docker
        run: make build ./receiver/Dockerfile


  push:
    runs-on: ubuntu-latest
    needs: build


