name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2



      - name: Login to the GitHub container registry endpoint
        run: docker login --username sarnik80 --password ${{ secrets.GH_PAT }} ghcr.io


      - name: Build And Push Docker Image ( sender )
        run: |
          make build  DOCKER_IMAGE_NAME="ghcr.io/sarnik80/sender:latest" DOCKERFILE="./sender/Dockerfile"
          make push  PATH_TO_PUSH="ghcr.io/sarnik80/sender:latest"

      - name: Build And Push Docker Image ( receiver )
        run: |
          make build  DOCKER_IMAGE_NAME="ghcr.io/sarnik80/receiver:latest" DOCKERFILE="./receiver/Dockerfile"
          make push PATH_TO_PUSH="ghcr.io/sarnik80/receiver:latest"