name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build-sender:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t sender:latest -f ./sender/Dockerfile .


  build-receiver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: push to docker
        run: docker build -t receiver:latest -f ./receiver/Dockerfile .

